#!/bin/sh
# vim: nospell

umask 007

check()
{
	command -v "$1" >/dev/null 2>/dev/null && return 0
	printf "Command not found: %s\n" "$1" >&2
	exit 255
}

test -r /etc/bpkg.conf && {
	. /etc/bpkg.conf
}

check make
check bpkg-checkbuilddeps
check make-package
check ar-stream
check tar-stream
check xz
check sha256sum
check sha512sum

DIR=${1:-.}

cd "$DIR"

if [ ! -r debian/control ]
then
	printf "No control file\n" >&2

	if [ -z "$1" ]
	then
		printf "Usage: %s [package directory] [version] [destination]\n" "$0" >&2
	fi

	exit 1
fi

# The name of the package can only be set from the control
# file with the Package: line.
NAME=`grep ^Package: debian/control`
NAME=${NAME#Package: }

# The version of a package can be defined in either the
# control file, or given on the command line.
# In the event both are supplied, they are required to match.
VERSION=`grep ^Version: debian/control`
VERSION=${VERSION#Version: }

if [ -z "$2" -a -z "$VERSION" ]
then
	printf "No version specified in debian/control or on the command line\n" >&2
	exit 1
fi

if [ -n "$2" -a -n "$VERSION" -a "$2" != "$VERSION" ]
then
	printf "Version in debian/control does not match CLI argument\n" >&2
fi

# Finalise the determined version
VERSION=${VERSION:-$2}

# Determins where the file is to be written to
DESTINATION=${3:-$DIR}

# Seal all variables
readonly NAME
readonly VERSION
readonly DESTINATION

if [ -e "${DESTINATION}/${NAME}_${VERSION}.deb" ]
then
	printf "${NAME}:${VERSION} already built\n" >&2
	exit 0
fi

# Supply --quiet to all make(1) calls unless we have an interactive
# terminal; this is intended to keep automated builds readable.
test -t 1 -a -t 2 && QUIET= || QUIET=--quiet

bpkg-checkbuilddeps && \
make $QUIET clean && \
make $QUIET build && \
make $QUIET manifest || {
	printf "Failed\n" >&2
	exit 1
}

# Get the disk size of everything in the package
xargs du -c --apparent-size <manifest >sizes

# Find the total line in the sizes
while read SIZE DIR
do
	test "$DIR" = total && break
done <sizes

rm -f sizes

test -w "debian/control" || {
	printf "Can not update debian/control file\n" >&2
	exit 1
}

cp "debian/control" "debian/control.orig" || {
	printf "Could not create temporary control file\n" >&2
	exit 1
}

exec 3>"debian/control"

while IFS= read -r LINE
do
	test -n "$LINE" || continue

	FIELD="${LINE%%:*}"

	test "$FIELD" = "Version" && continue
	test "$FIELD" = "Installed-Size" && continue
	test "$FIELD" = "Size" && continue
	test "$FIELD" = "File" && continue
	test "$FIELD" = "SHA256" && continue
	test "$FIELD" = "SHA512" && continue

	printf "%s\n" "$LINE" >&3
done <"debian/control.orig"

printf "Version: %s\n" "$VERSION" >&3
printf "Installed-Size: %d\n" "$SIZE" >&3

exec 3>&-

mkdir -vp "${DESTINATION}"
make-package . "${DESTINATION}/${NAME}_${VERSION}.deb"
STATUS=$?

mv "debian/control.orig" "debian/control" || {
	printf "Unable to restore original control file\n" >&2
}

exit $STATUS
