#!/bin/sh
# vim: nospell

umask 022

. "/etc/bpkg.conf"

mkdir -p "$DISTDIR"

checksum()
{
	printf "%s %d" `"${1}sum" "$2" | awk '{ print $1 }'` `stat -c %s "$2"`
}

compress()
{
	xz    -fk "$1"
	gzip  -fk "$1"
	bzip2 -fk "$1"
}

component_arch()
{
	DIR="$DISTDIR/$DIST/$COMPONENT/binary-$ARCH"
	PACKAGES=Packages

	mkdir -p "$DIR"
	test -r "$DIR/$PACKAGES" || touch "$DIR/$PACKAGES"

	test -r "$DIR/Release" || \
	cat >"$DIR/Release" <<- EOF
		Archive: $DIST
		Origin: $ORIGIN
		Acquire-By-Hash: no
		Component: $COMPONENT
		Architecture: $ARCH
	EOF

	find "$POOLDIR" -name "*.dat" -exec grep -e "Architecture: $ARCH" -l -e "Architecture: all" {} \+ | xargs sed -e "s@Filename: $BASEDIR/@Filename: @" >"$TMPDIR/packages"

	compress "$DIR/$PACKAGES"
}

for COMPONENT in $COMPONENTS
do
	for ARCH in $ARCHS
	do
		component_arch
	done

	mkdir -p "$DISTDIR/$DIST/$COMPONENT/i18n"

	for LANG in $LANGS
	do
		touch "$DISTDIR/$DIST/$COMPONENT/i18n/Translation-$LANG"
		compress "$DISTDIR/$DIST/$COMPONENT/i18n/Translation-$LANG"
	done
done

exec 3>"$DISTDIR/$DIST/Release"

cat <<- EOF >&3
	Origin: $ORIGIN
	Label: $ORIGIN
	Suite: $DIST
	Version: 1.0
	Codename: $CODENAME
	Date: `date -R`
	Architectures: $ARCHS
	Components: $COMPONENT
	Description: Local Package Repostiory for $ORIGIN
EOF

FILES=`find "$DISTDIR/$DIST" -type f ! -name Release ! -name Release.gpg ! -name InRelease -printf '%P '`

echo "SHA256:" >&3
for FILE in $FILES
do
	printf " %s %10d %s\n" `checksum sha256 "$DISTDIR/$DIST/$FILE"` "$FILE" >&3
done

echo "SHA512:" >&3
for FILE in $FILES
do
	printf " %s %10d %s\n" `checksum sha512 "$DISTDIR/$DIST/$FILE"` "$FILE" >&3
done

exec 3>&-

gpg --yes -qabs          -o "$DISTDIR/$DIST/Release.gpg" "$DISTDIR/$DIST/Release"
gpg --yes --clearsign -qaso "$DISTDIR/$DIST/InRelease"   "$DISTDIR/$DIST/Release"

exec 9>&-

