#!/bin/sh

. /etc/bpkg.conf

check()
{
	command -v "$1" >/dev/null 2>/dev/null && return 0
	printf "Command not found: %s\n" "$1" >&2
	exit 255
}

check make-package
check ar-stream
check tar-stream
check xz

mkdir -p "${POOLDIR}" || {
	echo "wat" >&2
	exit 1
}

DIR=${1:-.}

cd "$DIR"

if [ ! -r debian/control ]
then
	printf "No control file\n" >&2
	exit 1
fi

NAME=`grep ^Package: debian/control`
NAME=${NAME#Package: }

VERSION=`grep ^Version: debian/control`
VERSION=${VERSION#Version: }

test -e "${POOLDIR}/${NAME}_${VERSION}.deb" && {
	printf "${NAME}:${VERSION} already built\n" >&2
	exit 0
}

make clean && \
make build && \
make manifest && \
make-package "$DIR" "${POOLDIR}/${NAME}_${VERSION}.deb" && \
printf "Done\n" >&2 || {
	printf "Failed\n" >&2
	exit 1
}
