name: Test Bootstrapping

on: [push, pull_request]

jobs:
  build:
    name: Build + Valgrind
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run:  make deps && sudo apt install valgrind

    - name: Build
      run:  make debug

    - name: Valgrind
      run:  make valgrind

    - name: Install
      run:  make bootstrap
